version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ashenone
      MYSQL_DATABASE: harmony_database
      MYSQL_USER: kurisu
      MYSQL_PASSWORD: ashenone
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
