version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    depends_on:
      - php
  php:
    image: php:7.4-fpm
    volumes:
      - ./public:/var/www/public
