version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: custom-nginx-container
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom-php-container
    volumes:
      - ./public:/var/www/public
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: custom-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
